build: off

environment:
  PYPI_PASSWORD:
    secure: cTOEFT9KZZBMDVJgZzi9IpUKnJVxzESacNbQbFraRIA=

  matrix:
    - PYTHON_VERSION: "3.6"
      MINICONDA: "C:\\Miniconda3-x64"
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: "3.7"
      MINICONDA: "C:\\Miniconda3-x64"
      PYTHON_ARCH: "64"

platform:
  - x64

matrix:
    fast_finish: true

init:
  - ECHO %PYTHON_VERSION% %MINICONDA%

install:
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - conda create -q -n test-environment python=%PYTHON_VERSION% numpy~=1.19.0 scipy Cython
  - activate test-environment
  - python -m pip install --upgrade pip
  - pip install wheel twine pytest
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - pip install -e .[tests]

test_script:
  - python -m pytest --cov=cornac

after_test:
  - python setup.py bdist_wheel
  - ps: rm dist/*.egg

artifacts:
  - path: dist\*

deploy_script:
  - echo "Starting Artifact Deployment"
  # Make .pypirc file for twine
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =                             >> %USERPROFILE%\\.pypirc
  - echo     pypi                                    >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
  - echo username=qttruong                           >> %USERPROFILE%\\.pypirc
  - echo password=%PYPI_PASSWORD%                    >> %USERPROFILE%\\.pypirc
  # Upload to PyPI
  - set HOME=%USERPROFILE%
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") { Invoke-Expression "twine upload --skip-existing dist/*.whl" 2>$null } Else { write-output "Not on a tag on master, won't deploy to pypi"}
  - echo "Finished Artifact Deployment"